CREATE DATABASE photogroup

CREATE TABLE IF NOT EXISTS users (
    uid INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    admin BOOLEAN NOT NULL,
    PRIMARY KEY (uid)
);